Frontend Kickoff
wolox-training/mr-express-js pull request #1
Opened 2018-03-27 16:38 UTC by martinremis

## Summary
Add an index html with a red title and a basic scss structure.

## Screenshot
![image](https://user-images.githubusercontent.com/37807839/37981370-edd7f646-31c3-11e8-8e52-e7f91057bf32.png)

## Trello Card
https://trello.com/c/RSOUdhVZ/11-setup-del-proyecto

2018-03-27 23:48 UTC, FrankIglesias requested changes

2018-03-27 23:48 UTC, FrankIglesias commented on index.html
> +<!doctype html>
check indentation of the file.

2018-03-28 13:02 UTC, martinremis commented
@FrankIglesias Identation fixed fot html childs.

2018-03-28 21:08 UTC, FrankIglesias approved these changes

2018-03-28 21:29 UTC, FrankIglesias commented
Good job! :clap:

2018-04-03 13:34 UTC, merged