Page titles
wolox-training/mr-express-js pull request #3
Opened 2018-03-28 19:39 UTC by martinremis

## Summary
Add a title "component".

## Screenshot
![page title](https://user-images.githubusercontent.com/37807839/38052104-837fb9ee-32a6-11e8-84e3-8a3147b929c2.png)

## Trello Card
https://trello.com/c/UMAUGi7K/21-page-titles

2018-03-28 21:18 UTC, FrankIglesias requested changes

2018-03-28 21:18 UTC, FrankIglesias commented on index.html
> +    <img src="assets/triangle.svg" class="titles-img"/>
add an alt to the image

2018-03-28 21:18 UTC, FrankIglesias commented on scss/styles.scss
> +  font-size: 1.5em;
use px dimensions

2018-03-28 21:18 UTC, FrankIglesias commented on scss/titles.scss
> +  flex-flow: row nowrap;
`flex-direction: row`

2018-03-28 21:19 UTC, FrankIglesias commented on scss/styles.scss
> +* {
move this into equalizer

2018-03-28 21:20 UTC, FrankIglesias requested changes

2018-03-28 21:20 UTC, FrankIglesias commented on scss/styles.scss
> +.titles-img {
I think you don't need flex: 0 1;

2018-03-28 21:36 UTC, FrankIglesias commented
Also, define the images next to the titles as pseudo elements

2018-04-03 16:59 UTC, martinremis commented
I've also changed the content of style.scss to titles.scss and removed an unused css class (titles).

2018-04-03 18:43 UTC, FrankIglesias requested changes

2018-04-03 18:43 UTC, FrankIglesias commented on index.html
> +  <div class="titles">
I think that now there's no need of this external div

2018-04-03 20:52 UTC, FrankIglesias approved these changes

2018-04-03 21:02 UTC, merged