Content layout
wolox-training/mr-express-js pull request #5
Opened 2018-03-28 19:48 UTC by martinremis

## Summary
Add some other cards and a new title.

## Screenshot
![content-layout](https://user-images.githubusercontent.com/37807839/38052450-b04c6dae-32a7-11e8-99f3-c837de343a9a.png)

## Trello Card
https://trello.com/c/FuC2uY2A/23-content-layout

2018-03-28 21:25 UTC, FrankIglesias requested changes

2018-03-28 21:25 UTC, FrankIglesias commented on scss/tech.scss
>  .technologies {
Check indentation

2018-03-28 21:25 UTC, FrankIglesias commented on scss/titles.scss
> +  margin: 1em 2em;
use px

2018-04-03 18:02 UTC, martinremis commented
Fixed some issues from previous PRs: "alt" tag for images and new usage of a title.

2018-04-03 18:50 UTC, FrankIglesias requested changes

2018-04-03 18:50 UTC, FrankIglesias commented on index.html
> +    <div>
I think you don't need this div wrapper

2018-04-04 19:00 UTC, FrankIglesias requested changes

2018-04-04 19:00 UTC, FrankIglesias commented on scss/styles.scss
> +.bold {
move this to text file

2018-04-04 19:00 UTC, FrankIglesias commented on scss/tech.scss
> +	margin: 0 7em 4em 7em;
use px instead of em

2018-04-04 19:00 UTC, FrankIglesias commented on scss/tech.scss
> +	margin: .5em;
same

2018-04-04 19:00 UTC, FrankIglesias commented on scss/tech.scss
> +	margin: .5em;
same

2018-04-04 19:00 UTC, FrankIglesias commented on scss/tech.scss
> + }
Check indentation

2018-04-04 19:00 UTC, FrankIglesias commented on scss/titles.scss
> +  margin-left: -33px;
Why this margin?

2018-04-04 19:00 UTC, FrankIglesias commented
Also resolve conflicts

2018-04-04 20:12 UTC, FrankIglesias approved these changes
Excelent job!

2018-04-04 20:15 UTC, merged