Add the navbar
wolox-training/mr-express-js pull request #7
Opened 2018-03-28 19:56 UTC by martinremis

## Summary
Add a Navbar.

## Screenshot
![navbar1](https://user-images.githubusercontent.com/37807839/38052867-d9140052-32a8-11e8-8aea-25f50c69c55d.png)

## Trello Card
https://trello.com/c/qSJPvx8d/13-navbar

2018-03-28 21:28 UTC, FrankIglesias requested changes

2018-03-28 21:28 UTC, FrankIglesias commented on scss/application.scss
> +$big-text: 24px;
you can define this variables inside a `text.scss` file

2018-03-28 21:28 UTC, FrankIglesias commented on scss/navbar.scss
> +  background-color: white;
use a variable

2018-03-28 21:28 UTC, FrankIglesias commented on scss/navbar.scss
> +  margin: 2em;
use px

2018-03-28 21:28 UTC, FrankIglesias commented on scss/styles.scss
> +body {
The body should not have any style applied, define a container at least for the layout. maybe you can change this for a margin top to another component

2018-03-28 21:29 UTC, FrankIglesias commented
Great job definin variables for sizes, just a few changes!

2018-04-03 18:55 UTC, FrankIglesias requested changes
Check indentation

2018-04-03 18:55 UTC, FrankIglesias commented on scss/navbar.scss
> +  margin: 1em;
use px instead

2018-04-04 20:58 UTC, martinremis commented
Navbar new capture
![navbar3](https://user-images.githubusercontent.com/37807839/38334454-c22f18de-3831-11e8-871b-f66f02890e18.png)

2018-04-04 21:03 UTC, FrankIglesias approved these changes

2018-04-04 21:03 UTC, FrankIglesias commented on scss/navbar.scss
> +  background-color: $white;
check indentation

2018-04-04 21:03 UTC, merged